---
ansible_become: yes 
ansible_become_method: sudo
ansible_become_pass: "123123"
ansible_user: ubuntu
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

token: abcdef.0123456789abcdef
token_ttl: 24h0m0s
