controller:
  config:
    allow-snippet-annotations: "true"
    enable-modsecurity: "true"
    enable-opentelemetry: "true"
    enable-owasp-modsecurity-crs: "true"
    log-format-upstream: $proxy_add_x_forwarded_for - $remote_user [$time_local] "$request"
      $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length
      $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr
      $upstream_response_length $upstream_response_time $upstream_status $req_id
    opentelemetry-config: /etc/nginx/opentelemetry.toml
    opentelemetry-operation-name: HTTP $request_method $service_name $uri
    opentelemetry-trust-incoming-span: 'true'
    otel-max-export-batch-size: '512'
    otel-max-queuesize: '2048'
    otel-sampler: AlwaysOn
    otel-sampler-parent-based: 'false'
    otel-sampler-ratio: '1.0'
    otel-schedule-delay-millis: '5000'
    otlp-collector-host: xtb-prod-otel-collector.otel
    otlp-collector-port: '4317'
    upstream-keepalive-timeout: '20'
    use-forwarded-headers: 'true'
  extraEnvs:
  - name: OTEL_SERVICE_NAME
    value: ingress-nginx
  extraVolumeMounts:
  - mountPath: /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    name: owasp-rules-vol
    subPath: nginx-modsecurity.conf
  - mountPath: /etc/nginx/modsecurity/modsecurity.conf
    name: modsecurity-conf-vol
    subPath: modsecurity.conf
  - mountPath: /etc/nginx/owasp-modsecurity-crs/crs-setup.conf
    name: custom-rules-vol
    subPath: crs-setup.conf
  - mountPath: /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    name: custom-rules-vol
    subPath: REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  - mountPath: /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    name: custom-rules-vol
    subPath: REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
  - mountPath: /etc/nginx/owasp-modsecurity-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    name: custom-rules-vol
    subPath: RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
  - mountPath: /data/logs/ingress
    name: modsecurity-audit-log-vol
  extraVolumes:
  - configMap:
      defaultMode: 420
      name: owasp-rules-config
    name: owasp-rules-vol
  - configMap:
      defaultMode: 420
      name: custom-rules-config
    name: custom-rules-vol
  - emptyDir: {}
    name: modsecurity-audit-log-vol
  - configMap:
      name: modsecurity-config
    name: modsecurity-conf-vol
  image:
    tag: v1.7.0
  ingressClass: nginx-new
  ingressClassResource:
    controllerValue: k8s.io/ingress-nginx-new
    name: nginx-new
  opentelemetry:
    allowPrivilegeEscalation: false
    containerSecurityContext: null
    enabled: true
    image: registry.k8s.io/ingress-nginx/opentelemetry:v20230312-helm-chart-4.5.2-28-g66a760794@sha256:40f766ac4a9832f36f217bb0e98d44c8d38faeccbfe861fbc1a76af7e9ab257f
  service:
    external:
      enabled: false
    internal:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=false
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:211125450637:certificate/303fcf96-5771-4055-8280-329964c3bd88
        service.beta.kubernetes.io/aws-load-balancer-subnets: xtb-common-private-ap-southeast-1a-0
        service.beta.kubernetes.io/aws-load-balancer-type: external
      enabled: true
      externalTrafficPolicy: "Local"
    targetPorts:
      http: http
      https: http