---
- name: Creates Netowrk Addons directory
  file:
    path: "{{ network_dir }}/calico"
    state: directory

- name: Template Calico Config
  ansible.builtin.template:
    src: templates/custom-resources.yaml.j2
    dest: "{{ network_dir }}/calico/custom-resources.yaml"

- name: Install Tigera Operator
  shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/tigera-operator.yaml

- name: Install Calico Resources
  shell: |
    kubectl create -f {{ network_dir }}/calico/custom-resources.yaml