---
- name: Check if calico already installed
  stat:
    path: "{{ network_dir }}/calico/custom-resources.yaml"
  register: calico_conf
  when: 
    - network == "calico"

- name: Install Calico Addons
  include_tasks: calico.yml
  when: network == "calico" and not calico_conf.stat.exists

- name: Check if cilium already installed
  stat:
    path: "{{ network_dir }}/cilium/<file>"
  register: cilium_conf
  when: network == "cilium"

- name: Install Cilium Addons
  include_tasks: cilium.yml
  when: network == "cilium" and not cilium_conf.stat.exists