---
- name: Init Kube-master
  shell: |
    kubeadm init --token {{ token }} --token-ttl {{ token_ttl }} \
    --apiserver-advertise-address {{ master_ip }} \
    --apiserver-cert-extra-sans {{ additional_sans }} \
    --control-plane-endpoint {{ control_plane_endpoint }} \
    --pod-network-cidr {{ pod_network_cidr }} 

- name: Creates Kubernetes config directory
  file:
    path: ".kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy admin.conf to Home directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ".kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
    remote_src: true