---
- name: Start Containerd
  service: 
    name: containerd
    state: started
    enabled: yes

- name: Restart Containerd
  service: 
    name: containerd
    state: restarted

- name: Start kubelet
  service:
    name: kubelet
    enabled: true
    state: started

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted
